---
apiVersion: controllermanager.config.gardener.cloud/v1alpha1
kind: ControllerManagerConfiguration
gardenClientConnection:
  qps: 100
  burst: 130
controllers:
  plant:
    syncPeriod: 10s
    concurrentSyncs: 5
  seed:
    concurrentSyncs: 5
    syncPeriod: 30s
  # monitorPeriod: 40s
  # shootMonitorPeriod: 300s
  shootMaintenance:
    concurrentSyncs: 5
  # enableShootControlPlaneRestarter: true
  # enableShootCoreAddonRestarter: true
  shootHibernation:
    concurrentSyncs: 5
  shootQuota:
    concurrentSyncs: 5
    syncPeriod: 60m
  shootReference:
    concurrentSyncs: 5
    protectAuditPolicyConfigMaps: true
  shootRetry:
    concurrentSyncs: 5
  # retryDuration: 10m
  project:
    concurrentSyncs: 5
    minimumLifetimeDays: 30
    staleGracePeriodDays: 14
    staleExpirationTimeDays: 90
    staleSyncPeriod: 12h
  # quotas:
  # - config:
  #     apiVersion: v1
  #     kind: ResourceQuota
  #     spec:
  #       hard:
  #         count/shoots.core.gardener.cloud: "100"
  #         count/secretbindings.core.gardener.cloud: "10"
  #         count/secrets: "400"
  #   projectSelector: {}
  event:
    concurrentSyncs: 5
    ttlNonShootEvents: 1h
  managedSeedSet:
    concurrentSyncs: 5
  # maxShootRetries: 3
    syncPeriod: 30m
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  renewDeadline: 10s
  retryPeriod: 2s
  resourceLock: leases
logLevel: info
kubernetesLogLevel: 0
server:
  http:
    bindAddress: 0.0.0.0
    port: 2718
featureGates:
  CachedRuntimeClients: true
