---
apiVersion: scheduler.config.gardener.cloud/v1alpha1
kind: SchedulerConfiguration
clientConnection:
  qps: 100
  burst: 130
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  renewDeadline: 10s
  retryPeriod: 2s
  resourceLock: leases
logLevel: info
server:
  http:
    bindAddress: 0.0.0.0
    port: 10251
#schedulers:
#  backupBucket:
#    concurrentSyncs: 5 # defaults to 5
#    retrySyncPeriod: 15s # initial retry period, then uses exponential backoff
#  shoot:
#    concurrentSyncs: 5 # defaults to 5
#    retrySyncPeriod: 15s # initial retry period, then uses exponential backoff
#    candidateDeterminationStrategy: MinimalDistance # either {SameRegion,MinimalDistance}
featureGates:
  CachedRuntimeClients: true
