images:
  grafana: image-repository:image-tag
  busybox: image-repository:image-tag

ingress:
  class: nginx
  hosts:
  - hostName: g.seed-1.example.com
    secretName: grafana-tls
  # admin : admin base64 encoded
  basicAuthSecret: YWRtaW46JGFwcjEkSWRSaVM5c3MkR3U1MHMxaGUwL2Z6Tzh2elE4S1BEMQ==
replicas: 1
ports:
  prometheus: 9090
  grafana: 3000

vpaEnabled: false
role: operators
extensions:
  dashboards: ""

konnectivityTunnel:
  enabled: false

sni:
  enabled: false

exposedComponents:
- dashboardName: "Kube Apiserver"
  fileName: "kube-apiserver-logging.json"
  pods:
  - podPrefix: "kube-apiserver"
- dashboardName: "Kube Controller Manager"
  fileName: "kube-controller-manager-logging.json"
  pods:
  - podPrefix: "kube-controller-manager"
- dashboardName: "Kube Scheduler"
  fileName: "kube-scheduler-logging.json"
  pods:
  - podPrefix: "kube-scheduler"
- dashboardName: "Cluster Autoscaler"
  fileName: "cluster-autoscaler-logging.json"
  pods:
  - podPrefix: "cluster-autoscaler"
- dashboardName: "Vertical Pod Autoscaler"
  fileName: "vpa-logging.json"
  pods:
  - podPrefix: "vpa-admission-controller"
  - podPrefix: "vpa-recommender"
  - podPrefix: "vpa-updater"
