global:
  podNetwork: 1.2.3.4/24
kubeconfig: dummy-b64-data-here
kubernetesVersion: 1.15.2
#featureGates: {}
#  CustomResourceValidation: true
#  RotateKubeletServerCertificate: false
images:
  kube-proxy: image-repository
  alpine: image-repository
podAnnotations: {}

enableIPVS: false

ports:
  metrics: 10249
