apiVersion: {{ include "daemonsetversion" . }}
kind: DaemonSet
metadata:
  name: node-problem-detector
  labels:
    gardener.cloud/role: system-component
    app.kubernetes.io/name: {{ include "node-problem-detector.name" . }}
    helm.sh/chart: {{ include "node-problem-detector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    origin: gardener
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "node-problem-detector.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: {{ include "node-problem-detector.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "node-problem-detector.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ include "node-problem-detector.name" . }}
        gardener.cloud/role: system-component
        origin: gardener
        networking.gardener.cloud/to-apiserver: allowed
        networking.gardener.cloud/to-dns: allowed
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/custom-config-configmap.yaml") . | sha256sum }}
        scheduler.alpha.kubernetes.io/critical-pod: ''
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 8 }}
{{- end }}
    spec:
      dnsPolicy: Default # make sure to not use the coredns for DNS resolution.
      serviceAccountName: node-problem-detector
      hostNetwork: {{ .Values.hostNetwork }}
      terminationGracePeriodSeconds: 30
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image:  {{ index .Values.images "node-problem-detector" }}
          imagePullPolicy: {{ .Values.images.pullPolicy | default "IfNotPresent" | quote }}
          command:
            - "/bin/sh"
            - "-c"
            - "exec /node-problem-detector --logtostderr --config.system-log-monitor={{- range $index, $monitor := .Values.settings.log_monitors }}{{if ne $index 0}},{{end}}{{ $monitor }}{{- end }} .. {{- if .Values.settings.custom_plugin_monitors }} --config.custom-plugin-monitor={{- range $index, $monitor := .Values.settings.custom_plugin_monitors }}{{if ne $index 0}},{{end}}{{ $monitor }}{{- end }} {{- end }} .. {{- if .Values.settings.system_stats_monitor }} --config.system-stats-monitor={{- range $index, $monitor := .Values.settings.system_stats_monitor }}{{if ne $index 0}},{{end}}{{ $monitor }}{{- end }} {{- end }} --prometheus-address={{ .Values.settings.prometheus_address }} --prometheus-port={{ .Values.settings.prometheus_port }}"
          securityContext:
            privileged: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
{{- if .Values.env }}
{{ toYaml .Values.env | indent 12 }}
{{- end }}
          volumeMounts:
            - name: log
              mountPath: /var/log
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: kmsg
              mountPath: /dev/kmsg
              readOnly: true
            - name: custom-config
              mountPath: /custom-config
              readOnly: true
          ports:
            - containerPort: {{ .Values.settings.prometheus_port }}
              name: exporter
          resources:
            requests:
              cpu: 20m
              memory: 20Mi
            limits:
            {{- if .Values.global.vpaEnabled }}
              cpu: 80m
              memory: 80Mi
            {{- else }}
              cpu: 200m
              memory: 100Mi
            {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      volumes:
        - name: log
          hostPath:
            path: {{ .Values.hostpath.logdir }}
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: "FileOrCreate"
        - name: kmsg
          hostPath:
            path: /dev/kmsg
        - name: custom-config
          configMap:
            name: node-problem-detector-custom-config
