apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Target
metadata:
  name: seed-cluster
  namespace: default
spec:
  type: landscaper.gardener.cloud/kubernetes-cluster
  config:
    kubeconfig: |
      apiVersion:...
          # here goes the kubeconfig of the runtime cluster
