apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-exporter
  namespace: kube-system
  labels:
    component: node-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: kube-system
  labels:
    component: node-exporter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.ports.metrics }}
    protocol: TCP
  selector:
    component: node-exporter
---
apiVersion: {{ include "daemonsetversion" . }}
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: kube-system
  labels:
    gardener.cloud/role: monitoring
    component: node-exporter
    origin: gardener
spec:
  selector:
    matchLabels:
      component: node-exporter
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
      labels:
        networking.gardener.cloud/to-public-networks: allowed
        networking.gardener.cloud/from-seed: allowed
        gardener.cloud/role: monitoring
        origin: gardener
        component: node-exporter
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      hostNetwork: true
      hostPID: true
      priorityClassName: system-cluster-critical
      serviceAccountName: node-exporter
      # not used - safe to not mount it at all.
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
      - name: node-exporter
        image: {{ index .Values.images "node-exporter" }}
        imagePullPolicy: IfNotPresent
        command:
        - /bin/node_exporter
        - --web.listen-address=:{{ .Values.ports.metrics }}
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        - --path.rootfs=/host
        - --log.level=error
        - --collector.disable-defaults
        - --collector.conntrack
        - --collector.cpu
        - --collector.filefd
        - --collector.filesystem
        - --collector.filesystem.ignored-mount-points=^/.+$
        - --collector.loadavg
        - --collector.meminfo
        - --collector.uname
        ports:
        - containerPort: {{ .Values.ports.metrics }}
          protocol: TCP
          hostPort: {{ .Values.ports.metrics }}
          name: scrape
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.ports.metrics }}
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.ports.metrics }}
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - name: host
          readOnly: true
          mountPath: /host
      volumes:
      - name: host
        hostPath:
          path: /
