{{- if .Values.global.vpaEnabled }}
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: node-exporter
  namespace: {{ .Release.Namespace }}
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 50m
          memory: 50Mi
  targetRef:
    apiVersion: {{ include "daemonsetversion" . }}
    kind: DaemonSet
    name: node-exporter
  updatePolicy:
    updateMode: "Auto"
{{- end }}
