apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: {{ .Release.Namespace }}
  annotations:
    # Deprecated: These AWS-specific annotation are deprecated. You need to apply them via
    # the '.spec.settings.loadBalancerServices.annotations' field of the Seed.
    # TODO (mvladev): remove the annotations in v1.17.0
    service.alpha.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
{{- if .Values.annotations }}
{{ .Values.annotations | toYaml | indent 4 }}
{{- end }}
  labels:
{{ .Values.labels | toYaml | indent 4 }}
spec:
  type: {{ .Values.serviceType }}
  selector:
{{ .Values.labels  | toYaml | indent 4 }}
  ports:
  - name: status-port
    port: 15021
    targetPort: 15021
    protocol: TCP
{{- if .Values.ports }}
{{ toYaml .Values.ports | indent 2 }}
{{- end }}
