{{- if .Values.konnectivityTunnel.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-apiserver-egress-selector-configuration
  namespace: {{.Release.Namespace}}
data:
  egress-selector-configuration.yaml: |-
    apiVersion: apiserver.k8s.io/v1alpha1
    kind: EgressSelectorConfiguration
    egressSelections:
    - name: cluster
      connection:
        proxyProtocol: HTTPConnect
        transport:
          {{- if .Values.sni.enabled }}
          tcp:
            url: https://konnectivity-server:9443
            tlsConfig:
              caBundle: /srv/kubernetes/ca/ca.crt
              clientCert: /etc/srv/kubernetes/konnectivity-server-client-tls/tls.crt
              clientKey: /etc/srv/kubernetes/konnectivity-server-client-tls/tls.key
          {{- else }}
          uds:
            udsName: /etc/srv/kubernetes/konnectivity-server/konnectivity-server.socket
          {{- end }}
    - name: {{ if semverCompare "< 1.20" .Values.kubernetesVersion }}master{{ else }}controlplane{{ end }}
      connection:
        proxyProtocol: Direct
    - name: etcd
      connection:
        proxyProtocol: Direct
{{- end }}
{{- if .Values.reversedVPN.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-apiserver-egress-selector-configuration
  namespace: {{.Release.Namespace}}
data:
  egress-selector-configuration.yaml: |-
    apiVersion: apiserver.k8s.io/v1alpha1
    kind: EgressSelectorConfiguration
    egressSelections:
    - name: cluster
      connection:
        proxyProtocol: HTTPConnect
        transport:
          tcp:
            url: https://vpn-seed-server:9443
            tlsConfig:
              caBundle: /etc/srv/kubernetes/envoy/ca.crt
              clientCert: /etc/srv/kubernetes/envoy/tls.crt
              clientKey: /etc/srv/kubernetes/envoy/tls.key
    - name: {{ if semverCompare "< 1.20" .Values.kubernetesVersion }}master{{ else }}controlplane{{ end }}
      connection:
        proxyProtocol: Direct
    - name: etcd
      connection:
        proxyProtocol: Direct
{{- end }}
