{{- if and .Values.konnectivityTunnel.enabled (not .Values.sni.enabled) }}
apiVersion: {{ include "rbacversion" . }}
kind: Role
metadata:
  name: konnectivity-server
  namespace: {{ .Release.Namespace }}
  labels:
    gardener.cloud/role: controlplane
    app: kubernetes
    role: apiserver
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - watch
  - list
  resourceNames:
  - kube-apiserver
---

apiVersion: {{ include "rbacversion" . }}
kind: RoleBinding
metadata:
  name: konnectivity-server
  namespace: {{ .Release.Namespace }}
  labels:
    gardener.cloud/role: controlplane
    app: kubernetes
    role: apiserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: konnectivity-server
subjects:
- kind: ServiceAccount
  name: kube-apiserver
{{- end }}
