{{- if .Values.konnectivityTunnel.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    gardener.cloud/role: controlplane
    app: kubernetes
    role: apiserver
{{- end }}
