# The values here match the ones on the upstream deployment repo (https://github.com/coredns/deployment/blob/master/kubernetes/coredns.yaml.sed).
# They may need to be updated in the future

global:
  podNetwork: 1.2.3.4/24
nodeNetwork: 2.3.4.5/24
service:
  type: "ClusterIP"
  clusterDNS: 100.64.0.10
  domain:
    clusterDomain: cluster.local
    additionalDomains: in-addr.arpa ip6.arpa
  port: 53
  targetPort: 8053
  annotations: {}
  metricsPort: 9153
images:
   coredns: image-repository:image-tag
deployment:
  spec:
    podAnnotations: {}
    containers:
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 250m
          memory: 500Mi
        requests:
          cpu: 50m
          memory: 15Mi
      ports:
        dns: 8053

configmap:
  servers:
  - zones:
    - zone: .
    port: 8053
    plugins:
    - name: errors
    - name: log
      parameters: .
      configBlock: |-
        class error
    - name: health
    - name: ready
    - name: kubernetes
      parameters: cluster.local in-addr.arpa ip6.arpa
      configBlock: |-
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
        ttl 30
    - name: prometheus
      parameters: 0.0.0.0:9153
    - name: forward
      parameters: . /etc/resolv.conf
    - name: cache
      parameters: 30
    - name: loop
    - name: reload
    - name: loadbalance
      parameters: round_robin
    - name: import
      parameters: custom/*.override
  zoneFiles: []  # configure custom zone files as per https://coredns.io/2017/05/08/custom-dns-entries-for-kubernetes/
  #  - filename: example.db
  #    domain: example.com
  #    contents: |
  #      example.com.   IN SOA sns.dns.icann.com. noc.dns.icann.com. 2015082541 7200 3600 1209600 3600
  #      example.com.   IN NS  b.iana-servers.net.
  #      example.com.   IN NS  a.iana-servers.net.
  #      example.com.   IN A   192.168.99.102
  #      *.example.com. IN A   192.168.99.102

horizontalPodAutoScaler:
  spec:
    maxReplicas: 5
    minReplicas: 2
    metrics:
      targetAverageUtilization: 70
# kubeAPIServerHost: foo.bar
