apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
    role: monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-web
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
    role: monitoring
spec:
  ports:
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector:
    app: prometheus
    role: monitoring
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: {{include "statefulsetversion" .}}
kind: StatefulSet
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    gardener.cloud/role: monitoring
    app: prometheus
    role: monitoring
spec:
  updateStrategy:
    type: RollingUpdate
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: prometheus
      role: monitoring
  serviceName: prometheus
  template:
    metadata:
      annotations:
        checksum/configmap-blackbox-exporter: {{ include (print $.Template.BasePath "/blackbox-exporter-config.yaml") . | sha256sum }}
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        gardener.cloud/role: monitoring
        garden.sapcloud.io/role: monitoring
        app: prometheus
        role: monitoring
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-public-networks: allowed
        networking.gardener.cloud/to-shoot-networks: allowed
        networking.gardener.cloud/to-shoot-apiserver: allowed
        networking.gardener.cloud/to-seed-apiserver: allowed
    spec:
      # used to talk to Seed's API server.
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: {{ index .Values.images "prometheus" }}
        imagePullPolicy: IfNotPresent
        args:
        - --config.file=/etc/prometheus/config/prometheus.yaml
        - --storage.tsdb.path=/var/prometheus/data
        - --storage.tsdb.no-lockfile
        - --storage.tsdb.retention.time=30d
        - --storage.tsdb.retention.size=15GB
        - --web.route-prefix=/
        - --web.enable-lifecycle
        - --web.listen-address=0.0.0.0:{{ .Values.port }}
        - --web.external-url=https://{{ .Values.ingress.host }}
        # Since v2.0.0-beta.3 prometheus runs as nobody user (fsGroup 65534/runAsUser 0)
        # data volume needs to be mounted with the same permissions,
        # otherwise we will have Permission denied problems
        securityContext:
          runAsUser: 0
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: {{ .Values.port }}
            scheme: HTTP
          failureThreshold: 60
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /-/ready
            port: {{ .Values.port }}
            scheme: HTTP
          failureThreshold: 120
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        ports:
        - name: web
          containerPort: 9090
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 350Mi
        volumeMounts:
        - mountPath: /srv/kubernetes/prometheus-kubelet
          name: prometheus-kubelet
        - mountPath: /srv/kubernetes/etcd/ca
          name: ca-etcd
        - mountPath: /srv/kubernetes/etcd/client
          name: etcd-client-tls
        - mountPath: /etc/prometheus/config
          name: config
          readOnly: true
        - mountPath: /etc/prometheus/rules
          name: rules
          readOnly: true
        - mountPath: /var/prometheus/data
          name: prometheus-db
          subPath: prometheus-
        # we mount the Shoot cluster's CA and certs
        - mountPath: /etc/prometheus/seed
          name: prometheus-kubeconfig
        {{- if hasKey .Values.alerting.auth_type "certificate" }}
        - mountPath: /etc/prometheus/operator
          name: prometheus-remote-am-tls
        {{- end }}
      - name: blackbox-exporter
        image: {{ index .Values.images "blackbox-exporter" }}
        args:
        - --config.file=/vpn/blackbox.yaml
        - --web.listen-address=127.0.0.1:9115
        ports:
        # port name must be max 15 characters long
        - name: blackbox-export
          containerPort: 9115
          protocol: TCP
        resources:
          requests:
            cpu: 5m
            memory: 35Mi
          limits:
            cpu: 50m
            memory: 128Mi
        volumeMounts:
        - name: blackbox-exporter-config-prometheus
          mountPath: /vpn
        - mountPath: /var/run/secrets/blackbox
          name: prometheus-kubeconfig
          readOnly: true
      - name: prometheus-config-reloader
        image: {{ index .Values.images "configmap-reloader" }}
        imagePullPolicy: IfNotPresent
        args:
        - -webhook-url=http://localhost:{{ .Values.port }}/-/reload
        - -volume-dir=/etc/prometheus/config
        - -volume-dir=/etc/prometheus/rules
        resources:
          requests:
            cpu: 5m
            memory: 25Mi
          limits:
            cpu: 10m
            memory: 25Mi
        volumeMounts:
        - mountPath: /etc/prometheus/config
          name: config
          readOnly: true
        - mountPath: /etc/prometheus/rules
          name: rules
          readOnly: true
      terminationGracePeriodSeconds: 60
      volumes:
      - name: config
        configMap:
          defaultMode: 420
          name: prometheus-config
      - name: rules
        configMap:
          defaultMode: 420
          name: prometheus-rules
      - name: shoot-ca
        secret:
          defaultMode: 420
          secretName: ca
      - name: ca-etcd
        secret:
          secretName: ca-etcd
      - name: etcd-client-tls
        secret:
          secretName: etcd-client-tls
      - name: prometheus-kubeconfig
        secret:
          secretName: prometheus
      - name: prometheus-kubelet
        secret:
          secretName: prometheus-kubelet
      - name: blackbox-exporter-config-prometheus
        configMap:
          name: blackbox-exporter-config-prometheus
{{- if hasKey .Values.alerting.auth_type "certificate" }}
      - name: prometheus-remote-am-tls
        secret:
          secretName: prometheus-remote-am-tls
{{- end }}
  volumeClaimTemplates:
  - metadata:
      name: prometheus-db
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.storage }}
