apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ .Release.Namespace }}
  namespace: {{ .Values.istioIngressGateway.namespace }}
  ownerReferences:
  - apiVersion: v1
    kind: Namespace
    name: {{ .Release.Namespace }}
    uid: {{ .Values.namespaceUID }}
    controller: false
    blockOwnerDeletion: false
spec:
  workloadSelector:
    labels:
{{ .Values.istioIngressGateway.labels | toYaml | trim | indent 6 }}
  configPatches:
  - applyTo: FILTER_CHAIN
    match:
      context: ANY
      listener:
        portNumber: 8443
        name: 0.0.0.0_8443
    patch:
      operation: ADD
      value:
        filters:
        - name: envoy.filters.network.tcp_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            stat_prefix: "outbound|443||{{ .Values.name }}.{{ .Release.Namespace }}.svc.cluster.local"
            cluster: "outbound|443||{{ .Values.name }}.{{ .Release.Namespace }}.svc.cluster.local"
        filter_chain_match:
          destination_port: 443
          prefix_ranges:
          - address_prefix: {{ .Values.apiserverClusterIP }}
            prefix_len: 32
  {{- if .Values.reversedVPN.enabled }}
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        name: 0.0.0.0_8132
        portNumber: 8132
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: "envoy.filters.network.http_connection_manager"
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          route_config:
            virtual_hosts:
            - name: {{ .Release.Namespace }}
              domains:
              - {{ .Values.internalDNSNameApiserver }}:8132
              routes:
              - match:
                  connect_matcher: {}
                route:
                  cluster: outbound|1194||vpn-seed-server.{{ .Release.Namespace }}.svc.cluster.local
                  upgrade_configs:
                  - upgrade_type: CONNECT
                    connect_config: {}
  {{- end }}
