apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: apiserver
spec:
  selector:
{{ .Values.istioIngressGateway.labels | toYaml | trim | indent 4 }}
  servers:
  - hosts:
{{ toYaml .Values.hosts | indent 4 }}
    port:
      number: 443
      name: tls
      protocol: TLS
    tls:
      mode: PASSTHROUGH
