apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: apiserver
spec:
  exportTo:
  - "*"
  hosts:
{{ toYaml .Values.hosts | indent 2 }}
  gateways:
  - {{ .Values.name }}
  tls:
  - match:
    - port: 443
      sniHosts:
{{ toYaml .Values.hosts | indent 6 }}
    route:
    - destination:
        host: {{ .Values.name }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 443
